//! PDF evidence bundle export (v1.1.0 → v1.1.1).
//!
//! Per Plan v1.1 (Block 4 v1.1.0-US-10): "PDF export of evidence bundles"
//! — produce a human-readable PDF that an auditor can print, sign, and
//! attach to a regulatory file. JSON-only was the v1.0 limitation.
//!
//! ## What this module does
//!
//! Takes an evidence bundle (JSON string or `EvidenceBundle` struct)
//! and renders a multi-section PDF with:
//!
//! 1. **Header**: bundle_id, org_id, created_at, compliance rollup
//!    with most-restrictive-wins color coding (green=Compliant,
//!    yellow=Partial, red=NonCompliant, gray=Unknown).
//! 2. **Disclosures**: each disclosure's id, compliance, disclaimers.
//! 3. **Signature**: COSE_Sign1 (truncated to 80 chars + elision),
//!    issuer public key fingerprint (BLAKE3 hex), row hash.
//! 4. **Timestamp**: TSA token presence (FreeTSA/Sectigo/Mock label).
//! 5. **Verification instructions**: how to verify offline.
//! 6. **Disclaimers**: full list of v1 scope limitations.
//!
//! ## F23 (PDF writer replacement)
//!
//! `printpdf 0.9.1` was replaced by the in-tree `tl-pdf-core`
//! crate (a hand-rolled PDF 1.4 emitter, no external PDF deps) to
//! eliminate 9 transitive RUSTSECs (lopdf, ttf-parser, bincode,
//! fxhash, kuchiki, allsorts, azul-layout, ouroboros,
//! proc-macro-error). The public API (`parse_bundle`,
//! `render_bundle_pdf`, `render_json_to_pdf`, and the data
//! structs `EvidenceBundle`, `DisclosureItem`, `SignatureInfo`,
//! `PdfExportError`) is preserved.

use serde::{Deserialize, Serialize};
use thiserror::Error;
use tl_pdf_core::{
    BuiltinFont, ContentOps, PdfDocumentBuilder, Rgb as CoreRgb,
};

/// Errors from PDF export.
#[derive(Debug, Error)]
pub enum PdfExportError {
    #[error("invalid bundle JSON: {0}")]
    InvalidJson(String),
    #[error("missing required field: {0}")]
    MissingField(String),
    /// F23: rename of the previous `PrintPdf` variant — the
    /// underlying PDF dep is now the in-tree `tl-pdf-core`
    /// crate, not `printpdf`. Kept the variant name as a
    /// back-compat alias for any external callers that pattern-
    /// match on the error kind.
    #[error("pdf core error: {0}")]
    PdfCore(String),
}

/// Evidence bundle subset needed for PDF rendering.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct EvidenceBundle {
    #[serde(default)]
    pub bundle_id: String,
    #[serde(default)]
    pub org_id: String,
    #[serde(default)]
    pub created_at: String,
    #[serde(default)]
    pub compliance_rollup: String,
    #[serde(default)]
    pub disclosures: Vec<DisclosureItem>,
    #[serde(default)]
    pub signature: Option<SignatureInfo>,
    #[serde(default)]
    pub tsa_token: Option<String>,
    #[serde(default)]
    pub tsa_url: Option<String>,
    #[serde(default)]
    pub disclaimers: Vec<String>,
    #[serde(default)]
    pub row_hash: Option<String>,
    #[serde(default)]
    pub issuer_pubkey_fingerprint: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DisclosureItem {
    #[serde(default)]
    pub disclosure_id: String,
    #[serde(default)]
    pub compliance_rollup: String,
    #[serde(default)]
    pub v1_disclaimers: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SignatureInfo {
    #[serde(default)]
    pub cose_sign1_b64: String,
    #[serde(default)]
    pub row_hash: String,
}

/// Parse an evidence bundle from JSON.
pub fn parse_bundle(json: &str) -> Result<EvidenceBundle, PdfExportError> {
    let bundle: EvidenceBundle =
        serde_json::from_str(json).map_err(|e| PdfExportError::InvalidJson(e.to_string()))?;
    Ok(bundle)
}

/// Render an evidence bundle to PDF bytes.
///
/// Returns the raw PDF byte buffer. The caller is responsible for
/// writing it to disk or streaming it as an HTTP response.
pub fn render_bundle_pdf(bundle: &EvidenceBundle) -> Result<Vec<u8>, PdfExportError> {
    // We build the document in two passes: first construct the
    // document builder with all pages attached, then call
    // `into_bytes`. To stay compatible with the printpdf 0.9
    // pagination model, we use a small helper struct that
    // holds the current page's content ops + cursor y, and
    // flushes to a new page when the y falls below the
    // bottom-margin.
    let mut doc = PdfDocumentBuilder::new(&format!(
        "TrustLayer Evidence Bundle {}",
        bundle.bundle_id
    ));
    let mut current = PageState::new();

    // ─── Header ───────────────────────────────────────────────
    current.push_text(
        BuiltinFont::HelveticaBold,
        18.0,
        15.0,
        "TrustLayer Evidence Bundle",
    );
    current.y -= 8.0;
    current.push_text(
        BuiltinFont::Helvetica,
        10.0,
        15.0,
        "Generated by Apohara TrustLayer v1.2",
    );
    current.y -= 12.0;
    current.push_hline(15.0, current.y, 180.0);
    current.y -= 8.0;

    // ─── Bundle metadata ──────────────────────────────────────
    current.push_text(
        BuiltinFont::HelveticaBold,
        12.0,
        15.0,
        "Bundle Metadata",
    );
    current.y -= 7.0;
    current.push_kv(BuiltinFont::Helvetica, 15.0, "Bundle ID:", &bundle.bundle_id);
    current.y -= 6.0;
    current.push_kv(BuiltinFont::Helvetica, 15.0, "Org ID:", &bundle.org_id);
    current.y -= 6.0;
    current.push_kv(BuiltinFont::Helvetica, 15.0, "Created at:", &bundle.created_at);
    current.y -= 6.0;
    let rollup_color = rollup_to_core(&bundle.compliance_rollup);
    current.push_kv_colored(
        BuiltinFont::HelveticaBold,
        15.0,
        "Compliance:",
        &bundle.compliance_rollup,
        rollup_color,
    );
    current.y -= 10.0;
    current.push_hline(15.0, current.y, 180.0);
    current.y -= 8.0;

    // ─── Disclosures ──────────────────────────────────────────
    current.push_text(BuiltinFont::HelveticaBold, 12.0, 15.0, "Disclosures");
    current.y -= 7.0;
    if bundle.disclosures.is_empty() {
        current.push_text(BuiltinFont::Helvetica, 10.0, 15.0, "(no disclosures)");
        current.y -= 6.0;
    } else {
        for (i, disc) in bundle.disclosures.iter().enumerate() {
            current.push_text(
                BuiltinFont::HelveticaBold,
                10.0,
                15.0,
                &format!(
                    "{}. {} ({})",
                    i + 1,
                    disc.disclosure_id,
                    disc.compliance_rollup
                ),
            );
            current.y -= 5.5;
            for disclaimer in &disc.v1_disclaimers {
                current.y = current.push_wrapped_text(
                    BuiltinFont::Helvetica,
                    9.0,
                    20.0,
                    &format!("\u{2022} {}", disclaimer),
                    160.0,
                );
                current.y -= 4.5;
                if current.y < 30.0 {
                    flush_page(&mut doc, &mut current);
                }
            }
            current.y -= 2.0;
            if current.y < 30.0 {
                flush_page(&mut doc, &mut current);
            }
        }
    }
    current.y -= 4.0;
    current.push_hline(15.0, current.y, 180.0);
    current.y -= 8.0;

    // ─── Signature ───────────────────────────────────────────
    current.push_text(BuiltinFont::HelveticaBold, 12.0, 15.0, "Signature");
    current.y -= 7.0;
    if let Some(sig) = &bundle.signature {
        let truncated = truncate_cose(&sig.cose_sign1_b64, 80);
        current.push_kv(BuiltinFont::Courier, 15.0, "COSE_Sign1:", &truncated);
        current.y -= 6.0;
        current.push_kv(BuiltinFont::Courier, 15.0, "Row hash:", &sig.row_hash);
        current.y -= 6.0;
    } else {
        current.push_text(BuiltinFont::Helvetica, 10.0, 15.0, "(no signature)");
        current.y -= 6.0;
    }
    if let Some(fp) = &bundle.issuer_pubkey_fingerprint {
        current.push_kv(BuiltinFont::Courier, 15.0, "Issuer fp:", fp);
        current.y -= 6.0;
    }
    current.y -= 4.0;
    current.push_hline(15.0, current.y, 180.0);
    current.y -= 8.0;

    // ─── Timestamp ───────────────────────────────────────────
    current.push_text(BuiltinFont::HelveticaBold, 12.0, 15.0, "Timestamp");
    current.y -= 7.0;
    let tsa_label = match (&bundle.tsa_token, &bundle.tsa_url) {
        (Some(_), Some(url)) if url.contains("sectigo") => {
            "Sectigo qualified (EU AI Act Art. 50 compliant)"
        }
        (Some(_), Some(url)) if url.contains("digicert") => {
            "DigiCert qualified (EU AI Act Art. 50 compliant)"
        }
        (Some(_), Some(url)) if url.contains("free_tsa") || url.contains("freetsa") => {
            "FreeTSA \u{2014} DEMO ONLY (not EU Trust List qualified)"
        }
        (Some(_), Some(url)) if url.contains("mock") => "Mock \u{2014} DEMO ONLY",
        (Some(_), _) => "RFC 3161 token present (TSA provider unspecified)",
        (None, _) => "No RFC 3161 token",
    };
    current.push_kv(BuiltinFont::Helvetica, 15.0, "Provider:", tsa_label);
    current.y -= 6.0;
    if let Some(url) = &bundle.tsa_url {
        current.push_kv(BuiltinFont::Helvetica, 15.0, "URL:", url);
        current.y -= 6.0;
    }
    current.y -= 4.0;
    current.push_hline(15.0, current.y, 180.0);
    current.y -= 8.0;

    // ─── Disclaimers ─────────────────────────────────────────
    current.push_text(BuiltinFont::HelveticaBold, 12.0, 15.0, "Disclaimers");
    current.y -= 7.0;
    for disclaimer in &bundle.disclaimers {
        current.y = current.push_wrapped_text(
            BuiltinFont::Helvetica,
            9.0,
            15.0,
            disclaimer,
            160.0,
        );
        current.y -= 4.5;
        if current.y < 30.0 {
            flush_page(&mut doc, &mut current);
        }
    }
    current.y -= 4.0;
    current.push_hline(15.0, current.y, 180.0);
    current.y -= 8.0;

    // ─── Verification instructions ───────────────────────────
    current.push_text(
        BuiltinFont::HelveticaBold,
        12.0,
        15.0,
        "How to verify offline",
    );
    current.y -= 7.0;
    let instructions = "1. POST /v1/verify/provenance with bundle_id\n\
                        2. Or use openssl + the COSE_Sign1 envelope\n\
                        3. Or use the TrustLayer WASM SDK in a browser";
    let _ = current.push_wrapped_text(
        BuiltinFont::Helvetica,
        9.0,
        15.0,
        instructions,
        180.0,
    );

    // ─── Footer (on the trailing page) ───────────────────────
    current.push_text(
        BuiltinFont::Helvetica,
        8.0,
        15.0,
        "This PDF was generated by TrustLayer v1.2. It is a human-readable \
         rendering of the evidence bundle JSON and is NOT the canonical \
         evidence. The canonical evidence is the JSON bundle served at \
         GET /v1/evidence/{bundle_id} and the SCITT receipt at \
         GET /v1/evidence/{bundle_id}/scitt-receipt.",
    );

    // Flush the trailing page (if `content` is non-empty).
    if !current.content.as_bytes().is_empty() {
        flush_page(&mut doc, &mut current);
    }

    let bytes = doc
        .into_bytes()
        .map_err(|e| PdfExportError::PdfCore(format!("{e}")))?;
    Ok(bytes)
}

/// One-shot helper: parse JSON + render PDF.
pub fn render_json_to_pdf(json: &str) -> Result<Vec<u8>, PdfExportError> {
    let bundle = parse_bundle(json)?;
    render_bundle_pdf(&bundle)
}

// ─── helpers ─────────────────────────────────────────────────

/// Per-page accumulator: the current `ContentOps` plus the
/// y-cursor (mm from the bottom). When the cursor falls below the
/// bottom margin the page is flushed via
/// [`PdfDocumentBuilder::with_page`].
struct PageState {
    content: ContentOps,
    y: f32,
}

impl PageState {
    /// New empty page state. The y-cursor starts near the top
    /// of an A4 page (297mm tall, so 280mm = 17mm from the top).
    fn new() -> Self {
        Self {
            content: ContentOps::new(),
            y: 280.0,
        }
    }

    /// Append a `ShowText` op for `text` at `(x, self.y)` mm
    /// with the given font and size. The fill colour is set to
    /// black just before the text so previous colour changes
    /// don't leak.
    fn push_text(
        &mut self,
        font: BuiltinFont,
        size: f32,
        x: f32,
        text: &str,
    ) {
        let y = self.y;
        self.content
            .set_fill_rgb(CoreRgb(0.0, 0.0, 0.0))
            .begin_text()
            .set_font(font, size)
            .text_cursor(x * tl_pdf_core::MM_TO_PT, y * tl_pdf_core::MM_TO_PT)
            .show_text(text)
            .end_text();
    }

    /// `push_text` variant with an explicit y (does NOT update
    /// `self.y` — caller manages the cursor).
    fn push_text_at(
        &mut self,
        font: BuiltinFont,
        size: f32,
        x: f32,
        y: f32,
        text: &str,
    ) {
        self.content
            .set_fill_rgb(CoreRgb(0.0, 0.0, 0.0))
            .begin_text()
            .set_font(font, size)
            .text_cursor(x * tl_pdf_core::MM_TO_PT, y * tl_pdf_core::MM_TO_PT)
            .show_text(text)
            .end_text();
    }

    /// Key/value line at `(x, self.y)` mm. The key is left-
    /// justified into 14 chars.
    fn push_kv(&mut self, font: BuiltinFont, x: f32, key: &str, value: &str) {
        let line = format!("{:<14} {}", key, value);
        self.push_text(font, 10.0, x, &line);
    }

    /// Coloured key/value line at `(x, self.y)` mm. Resets the
    /// fill colour to black after emitting.
    fn push_kv_colored(
        &mut self,
        font: BuiltinFont,
        x: f32,
        key: &str,
        value: &str,
        color: (f32, f32, f32),
    ) {
        self.content.set_fill_rgb(CoreRgb(color.0, color.1, color.2));
        self.push_kv(font, x, key, value);
        self.content.set_fill_rgb(CoreRgb(0.0, 0.0, 0.0));
    }

    fn push_hline(&mut self, x: f32, y: f32, width: f32) {
        self.content
            .set_stroke_rgb(CoreRgb(0.7, 0.7, 0.7))
            .set_line_width(0.3)
            .hline(x, y, width)
            .set_stroke_rgb(CoreRgb(0.0, 0.0, 0.0))
            .set_line_width(1.0);
    }

    /// Wraps `text` to fit within `max_width_mm` at `size` pt and
    /// emits one `push_text` per line. Returns the new y position
    /// (top of the last emitted line) so the caller can update
    /// `self.y` if desired.
    fn push_wrapped_text(
        &mut self,
        font: BuiltinFont,
        size: f32,
        x: f32,
        text: &str,
        max_width_mm: f32,
    ) -> f32 {
        // Approximate 1 char = 0.18 × font_size mm wide (Helvetica).
        let chars_per_line = ((max_width_mm / (0.18 * size)) as usize).max(20);
        let mut current_line = String::new();
        let mut cur_y = self.y;
        for word in text.split_whitespace() {
            if current_line.len() + word.len() + 1 > chars_per_line && !current_line.is_empty() {
                self.push_text_at(font, size, x, cur_y, &current_line);
                cur_y -= size * 1.2;
                current_line.clear();
            }
            if !current_line.is_empty() {
                current_line.push(' ');
            }
            current_line.push_str(word);
        }
        if !current_line.is_empty() {
            self.push_text_at(font, size, x, cur_y, &current_line);
        }
        cur_y
    }
}

/// Move the current `PageState`'s content into a new page on the
/// document and reset the state for the next page.
fn flush_page(doc: &mut PdfDocumentBuilder, state: &mut PageState) {
    // Drain the ContentOps into a new PageBuilder and attach it.
    let mut page_builder = doc.add_page();
    let mut new_content = ContentOps::new();
    std::mem::swap(&mut new_content, &mut state.content);
    *page_builder.content_ops() = new_content;
    // `with_page` consumes self; swap to a temp, attach, swap back.
    let mut new_doc = PdfDocumentBuilder::new("");
    std::mem::swap(&mut new_doc, doc);
    new_doc = new_doc.with_page(page_builder);
    *doc = new_doc;
    state.y = 280.0;
}

fn truncate_cose(cose: &str, max: usize) -> String {
    if cose.len() <= max {
        cose.to_string()
    } else {
        format!("{}\u{2026}({} bytes total)", &cose[..max], cose.len())
    }
}

fn rollup_color(rollup: &str) -> (f64, f64, f64) {
    match rollup {
        "Compliant" => (0.0, 0.5, 0.0),    // green
        "Partial" => (0.8, 0.5, 0.0),      // amber
        "NonCompliant" => (0.7, 0.0, 0.0), // red
        _ => (0.4, 0.4, 0.4),              // gray
    }
}

fn rollup_to_core(rollup: &str) -> (f32, f32, f32) {
    let (r, g, b) = rollup_color(rollup);
    (r as f32, g as f32, b as f32)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_bundle_json() -> &'static str {
        r#"{
            "bundle_id": "disc-test-001",
            "org_id": "acme",
            "created_at": "2026-06-26T10:00:00Z",
            "compliance_rollup": "Partial",
            "disclosures": [
                {
                    "disclosure_id": "disc-test-001",
                    "compliance_rollup": "Partial",
                    "v1_disclaimers": ["watermark layer: NotApplicable in v1.0"]
                }
            ],
            "signature": {
                "cose_sign1_b64": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv4sH0...",
                "row_hash": "abcdef0123456789"
            },
            "tsa_token": "MIIR/jCCBuagAwIBAgIQD+8R0...",
            "tsa_url": "https://freetsa.org/tsr",
            "disclaimers": [
                "v1: Watermark=NotApplicable (image/audio deployers MUST wait for v1.1.1)",
                "FreeTSA timestamp: dev-only, not forensically valid"
            ]
        }"#
    }

    #[test]
    fn parse_valid_bundle() {
        let bundle = parse_bundle(sample_bundle_json()).unwrap();
        assert_eq!(bundle.bundle_id, "disc-test-001");
        assert_eq!(bundle.org_id, "acme");
        assert_eq!(bundle.compliance_rollup, "Partial");
        assert_eq!(bundle.disclosures.len(), 1);
        assert!(bundle.signature.is_some());
        assert_eq!(bundle.disclaimers.len(), 2);
    }

    #[test]
    fn parse_minimal_bundle() {
        let json = r#"{"bundle_id": "b1"}"#;
        let bundle = parse_bundle(json).unwrap();
        assert_eq!(bundle.bundle_id, "b1");
        assert_eq!(bundle.disclosures.len(), 0);
        assert!(bundle.signature.is_none());
    }

    #[test]
    fn parse_invalid_json_errors() {
        assert!(parse_bundle("not json").is_err());
        assert!(parse_bundle("").is_err());
    }

    #[test]
    fn render_bundle_pdf_produces_bytes() {
        let bundle = parse_bundle(sample_bundle_json()).unwrap();
        let bytes = render_bundle_pdf(&bundle).unwrap();
        assert!(!bytes.is_empty(), "PDF bytes should not be empty");
        assert!(
            bytes.starts_with(b"%PDF-"),
            "PDF should start with %PDF- magic bytes; got: {:?}",
            &bytes[..bytes.len().min(8)]
        );
    }

    #[test]
    fn render_json_to_pdf_end_to_end() {
        let bytes = render_json_to_pdf(sample_bundle_json()).unwrap();
        assert!(bytes.starts_with(b"%PDF-"));
    }

    #[test]
    fn render_minimal_bundle() {
        let bytes = render_json_to_pdf(r#"{"bundle_id": "minimal"}"#).unwrap();
        assert!(bytes.starts_with(b"%PDF-"));
    }

    #[test]
    fn rollup_color_coding() {
        assert_eq!(rollup_color("Compliant"), (0.0, 0.5, 0.0));
        assert_eq!(rollup_color("Partial"), (0.8, 0.5, 0.0));
        assert_eq!(rollup_color("NonCompliant"), (0.7, 0.0, 0.0));
        assert_eq!(rollup_color("Unknown"), (0.4, 0.4, 0.4));
        assert_eq!(rollup_color("anything-else"), (0.4, 0.4, 0.4));
    }

    #[test]
    fn truncate_cose_short() {
        assert_eq!(truncate_cose("abc", 80), "abc");
    }

    #[test]
    fn truncate_cose_long() {
        let long = "a".repeat(200);
        let truncated = truncate_cose(&long, 80);
        assert!(truncated.contains("\u{2026}"));
        assert!(truncated.contains("200 bytes total"));
    }

    #[test]
    fn tsa_label_free_tsa() {
        let label = render_for_label(r#"{"bundle_id":"b","tsa_url":"https://freetsa.org/x"}"#);
        // Just verify it doesn't error and produces valid PDF.
        assert!(label.starts_with(b"%PDF-"));
    }

    // Helper to render and check just the magic bytes.
    fn render_for_label(json: &str) -> Vec<u8> {
        render_json_to_pdf(json).unwrap()
    }

    #[test]
    fn render_with_many_disclosures_paginates() {
        // Build a bundle with 50 disclosures to force pagination.
        let mut disclosures = Vec::new();
        for i in 0..50 {
            disclosures.push(format!(
                r#"{{
                    "disclosure_id": "disc-{i}",
                    "compliance_rollup": "Partial",
                    "v1_disclaimers": [
                        "long disclaimer that should wrap across lines when rendered in the PDF output: {padding}",
                        "another disclaimer for disclosure {i}"
                    ]
                }}"#,
                i = i,
                padding = "x".repeat(120),
            ));
        }
        let json = format!(
            r#"{{
                "bundle_id": "big-bundle",
                "org_id": "acme",
                "created_at": "2026-06-26T10:00:00Z",
                "compliance_rollup": "Partial",
                "disclosures": [{}],
                "disclaimers": ["v1.2 disclaimer"]
            }}"#,
            disclosures.join(",")
        );
        let bytes = render_json_to_pdf(&json).unwrap();
        assert!(bytes.starts_with(b"%PDF-"));
        // PDF size scales with content; 50 disclosures with long
        // disclaimers should produce a multi-page PDF.
        assert!(bytes.len() > 5000, "multi-page PDF should be > 5KB");
    }
}
