//! Z3 SMT proof wrapper for INV-15.
//!
//! Absorbed from `Apohara_Context_Forge.apohara_context_forge.safety.z3_inv15_proof`
//! (Plan v3.0 W3.2). The original proof runs in Python with the `z3-solver`
//! package and returns UNSAT (PROVED) in 10.08 ms on the canonical
//! antecedent:
//!
//! ```text
//!     agent_role is judge-class (critic or judge)
//!     AND candidate_count >= 9
//!     AND reuse_rate = 0
//!     AND layout_shuffled = TRUE
//!     ==> use_dense_prefill = TRUE
//! ```
//!
//! This module embeds the canonical result (`UNSAT`, `10.08 ms`,
//! `z3 4.16.0`) so downstream callers can audit INV-15 compliance
//! without depending on the Z3 runtime. When the Z3 Python script
//! (`apohara_context_forge/safety/z3_inv15_proof.py`) is available
//! on disk, [`prove_inv15_via_subprocess`] re-runs it and parses the
//! JSON output, providing a fresh-witness check.

use serde::{Deserialize, Serialize};

use crate::{INV15_THEOREM, Z3_PROOF_ELAPSED_MS, Z3_VERSION};

/// Outcome of a Z3 proof attempt. Mirrors the Python
/// `prove_inv15()` return shape.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Z3ProofResult {
    /// `"PROVED"` (UNSAT on the negation) | `"COUNTEREXAMPLE"` (SAT) | `"UNKNOWN"`.
    pub status: ProofStatus,
    /// Theorem string. Always `"INV-15-DENSE-PREFILL"` for this crate.
    pub theorem: String,
    /// Z3 counterexample model (string-form) when status = `COUNTEREXAMPLE`.
    /// `None` for `PROVED` / `UNKNOWN`.
    pub model: Option<String>,
    /// Wall-clock time the Z3 solver took, in milliseconds.
    pub elapsed_ms: f64,
    /// Z3 version string (e.g. `"4.16.0"`).
    pub z3_version: String,
    /// Where this result came from.
    pub source: ProofSource,
}

impl Z3ProofResult {
    /// True iff the proof succeeded (UNSAT on the negation).
    pub fn is_proved(&self) -> bool {
        self.status == ProofStatus::Proved
    }
}

/// Proof outcome. Mirrors the Python `status` field.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum ProofStatus {
    /// Z3 returned UNSAT: the invariant holds for the modeled domain.
    Proved,
    /// Z3 returned SAT: a counterexample exists (INV-15 violated).
    Counterexample,
    /// Z3 returned UNKNOWN (e.g. timeout, unsupported logic).
    Unknown,
}

/// Where a [`Z3ProofResult`] came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProofSource {
    /// The canonical embedded result (no Z3 runtime needed).
    Embedded,
    /// Re-run via `z3_inv15_proof.py` over the Python interpreter.
    PythonSubprocess,
    /// Re-run via a future native Z3 binding (placeholder for follow-up work).
    NativeFuture,
}

/// Return the canonical embedded proof result. This is the UNSAT
/// (PROVED) result from the v6.0 ContextForge paper, generated by
/// `prove_inv15()` on `z3 4.16.0` over the canonical antecedent.
///
/// Always returns a `PROVED` result. Use [`prove_inv15_via_subprocess`]
/// to re-run Z3 and produce a fresh-witness check.
pub fn embedded_proof() -> Z3ProofResult {
    Z3ProofResult {
        status: ProofStatus::Proved,
        theorem: INV15_THEOREM.to_string(),
        model: None,
        elapsed_ms: Z3_PROOF_ELAPSED_MS,
        z3_version: Z3_VERSION.to_string(),
        source: ProofSource::Embedded,
    }
}

/// Try to re-run the original Python Z3 proof script via subprocess.
///
/// This is the optional path: when the `z3_inv15_proof.py` script is
/// available at `script_path` and `python3` (or `python`) is on PATH,
/// we invoke it and parse the JSON output. Falls back to
/// [`embedded_proof`] on any error (missing script, missing python,
/// non-zero exit, JSON parse failure). Callers that need a fresh
/// witness MUST inspect `result.source == ProofSource::PythonSubprocess`
/// to know the re-run actually happened.
pub fn prove_inv15_via_subprocess(script_path: &str) -> Z3ProofResult {
    let python = std::env::var("APOHARA_PYTHON").unwrap_or_else(|_| "python3".to_string());

    let output = std::process::Command::new(&python)
        .arg(script_path)
        .output();

    let output = match output {
        Ok(o) => o,
        Err(_) => return embedded_proof(),
    };

    if !output.status.success() {
        return embedded_proof();
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    let parsed: Result<SubprocessProofJson, _> = serde_json::from_str(stdout.trim());
    match parsed {
        Ok(j) => Z3ProofResult {
            status: match j.status.as_str() {
                "PROVED" => ProofStatus::Proved,
                "COUNTEREXAMPLE" => ProofStatus::Counterexample,
                _ => ProofStatus::Unknown,
            },
            theorem: j.theorem,
            model: j.model,
            elapsed_ms: j.elapsed_ms,
            z3_version: j.z3_version,
            source: ProofSource::PythonSubprocess,
        },
        Err(_) => embedded_proof(),
    }
}

/// Wire format for the Python script's JSON output. Private.
#[derive(Debug, Deserialize)]
struct SubprocessProofJson {
    status: String,
    theorem: String,
    model: Option<String>,
    elapsed_ms: f64,
    z3_version: String,
}
